baseURL = "http://spaste.oxasploits.com/"
languageCode = "en-us"
title = "The oxasploits secure pastebin"

[Params.Terminal]
schema = "goph"

  # [userName]@[pcName]:~/$ cd [workDir]
  # [userName]@[pcName]:~/[workDir]$ cat [profile]
  #
  # [description]
  #
  # Note: if you set Params.Tree > use = true
  # [userName]@[pcName]:~/[workDir]$ tree ./[folderName]/
  # ./[folderName]/
  # ...
  # Note: result of the tree command
  userName = "h4x0r"
  pcName = "oxasploits.com"
  workDir = "spaste"
  profile = "USEAGE"

  # Note: speed at which text is displayed on the terminal
  # Note: if set to 0, typing animation will be disabled
  # Note:
  # Note: if you want to enable Mathjax, you need to set it to 0
  # Note: and set "math: true" at front matter in your Markdown file
  ps1Delay = 0 # prompt speed : [userName]@[pcName]:~/$ , [userName]@[pcName]:~/[workDir]$
  stdoutDelay = 0 # stdout speed : [description] , files in Params.Tree
  commandDelay = 50 # command speed : cd [workDir] , cat [profile] , tree ./[folderName]/

  # terminalDelay = 20 : deprecated

  # Note: speed at which text is displayed on the activity pages
  # Note: if set to 0, typing animation will be disabled
  # Note: 
  # Note: if you want to enable Mathjax, you need to set it to 0
  # Note: and set "math: true" at front matter in your Markdown file
  titleDelay = 0 # title speed : "title" in front matter
  contentDelay = 0 # content speed : content in .md file

  # activityDelay = 5 : deprecated

  description = """
Spaste, a secure terminal paste tool.
Useage: 
&nbsp;&nbsp;&nbsp;&nbsp;cat /etc/passwd | ncat --ssl spaste.oxasploits.com 8888
&nbsp;&nbsp;&nbsp;&nbsp;cat /etc/passwd | openssl s_client -quiet -connect spaste.oxasploits.com:8888 2>/dev/null  

  """

  # Note: If you want to use a Markdown file, you can use the following
  # description = "/description.md"
  # Note: and put the description.md in /content/description.md

  [Params.Tree]
  use = true
  folderName = "spaste"
  # Note: ["ACTIVITY", "URL or PATH TO YOUR MARKDOWN FILE"]
  files = [ 
    ["README", "/src/README"],
    ["spaste.pl", "/src/spaste.pl"],
    ["spaste.crontab" , "/src/spaste.crontab"],
    ["spaste.service", "/src/spaste.service"],
  ]
